### ISSUE TITLE
Loading Timeline Under Windows System

### ISSUE THREAD

**Issue by Morais14** [theRanalyst/timelineJS_R#2]
When i try to load a Timeline under the Windows System a error message shows that couldn't not find the files in "www" folder, even if exist such a folder. I suspect that the app searches a path "www/" and not "www\" as in Windows System. Is this the problem or maybe i missed something?

**Comment by theRanalyst** [comment]
@Morais14 No, the Windows system allows for "/" and "\". The tool was developed and tested on Windows and is geared towards use on Windows. The issue, I assume, is that you have not created a "files" folder in which all of your local media content should be saved. Can you provide more details around the error?

**Comment by Morais14** [comment]
It was my mistake, I created the folder "www" and not the folder "www / files" as you pointed out. It works perfectly. I'm sorry for the inconvenience. And once again, congratulations for making the tool available to users of R.

**Comment by theRanalyst** [comment]
No worries at all! Please continue to post concerns and feedback as this tool is still very much in beta. I'm going to close this issue now as it appears to be solved.
